### ISSUE TITLE
undefined method `each_with_object' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by goemaeret** [atech/deployhq#1]
I've been using this CL tool for awhile now and it's just the thing we were looking for. Prior to today it worked like a charm, but as of today the tool just stopped working. I can't seem to deploy to any server anymore.

The client throws following error:

```
/usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/lib/deploy/cli.rb:99:in `deploy': undefined method `each_with_object' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/lib/deploy/cli.rb:53:in `invoke'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/bin/deployhq:5:in `<top (required)>'
	from /usr/local/bin/deployhq:22:in `load'
	from /usr/local/bin/deployhq:22:in `<main>'
```

I've also noticed some DeployHQ updates rolled out today so maybe it has something to do with these changes?

Sure hope you guys look into this.

Thanks!

**Comment by darkphnx** [comment]
Could you post the command you were trying to run when this occurred?

**Comment by goemaeret** [comment]
it occurs after i choose a server to deploy to (after i run the command **deployhq deploy**)...

this is the full output

```
$ deployhq deploy
1. prelive.golf.be (branch: default) (currently: b402ad2e95ddf4920eedd2a80e1485af8d3d73ef)
2. List Server Details
Please choose a server or group to deploy to:
1
/usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/lib/deploy/cli.rb:99:in `deploy': undefined method `each_with_object' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/lib/deploy/cli.rb:53:in `invoke'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deployhq-1.3.1/bin/deployhq:5:in `<top (required)>'
	from /usr/local/bin/deployhq:22:in `load'
	from /usr/local/bin/deployhq:22:in `<main>'
```

**Comment by darkphnx** [comment]
Found the offending change on the server side. Should all work as expected now.
